Реализован функционал по ТЗ дипломного проекта
Grigoriy-Popov/Explore-with-me pull request #1
Opened 2022-10-12 10:14 UTC by Grigoriy-Popov

2022-10-13 19:20 UTC, sergeymamonov requested changes
Пакеты именуются в snake_case. Ошибка в наименовании пакета participationRequest.

2022-10-13 19:20 UTC, sergeymamonov commented on ewm-service/src/main/resources/application.properties
> +#---
Зачем оставлять закомментированный код в проекте?

2022-10-13 19:20 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/EventServiceImpl.java
> +            views = (Integer) ((List<LinkedHashMap>) Objects.requireNonNull(responseEntity.getBody()))
Что приводится к типу Integer? ...get("hits")? Верно ли тогда расставлены скобки?

2022-10-13 19:20 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/exceptions/ErrorHandler.java
> +    }
А рантайм ошибка может произойти?

2022-10-13 19:40 UTC, Grigoriy-Popov commented on ewm-service/src/main/resources/application.properties
> +#---
это настройки для локального запуска в IDEA. Чтобы каждый раз в докере не запускать, оставил эти настройки.

2022-10-13 19:44 UTC, Grigoriy-Popov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/EventServiceImpl.java
> +            views = (Integer) ((List<LinkedHashMap>) Objects.requireNonNull(responseEntity.getBody()))
Добавил скобки

2022-10-13 19:53 UTC, Grigoriy-Popov commented on ewm-service/src/main/java/ru/practicum/explorewithme/exceptions/ErrorHandler.java
> +    }
добавил обработку RunTime exception

2022-10-14 05:06 UTC, Grigoriy-Popov commented
Не проходит тест на удаление категории, потому что тесты неправильно спроектированы. Для прохождения этого теста после удаления категории должен возвращаться null, а у меня выбрасывается исключение и приходит объект ApiError

2022-10-14 18:30 UTC, sergeymamonov approved these changes

2022-10-17 04:41 UTC, merged